const semanticClusters = [
  {
    id: "arrays",
    label: "ARRAY / C / LOOP STATE",
    domains: ["arrays"],
    x: -470,
    y: -220,
    rx: 330,
    ry: 215,
    rotate: -16,
    color: "#6aa4ff",
  },
  {
    id: "sorting",
    label: "SORTING / EXCHANGE",
    domains: ["sorting"],
    x: -250,
    y: -405,
    rx: 320,
    ry: 205,
    rotate: 7,
    color: "#d51f1f",
  },
  {
    id: "recursion",
    label: "RECURSION / DIVIDE",
    domains: ["recursion"],
    x: -650,
    y: -20,
    rx: 250,
    ry: 210,
    rotate: 14,
    color: "#f06f9a",
  },
  {
    id: "pointers",
    label: "POINTERS / MEMORY",
    domains: ["pointers"],
    x: -520,
    y: 190,
    rx: 290,
    ry: 210,
    rotate: -8,
    color: "#22a56a",
  },
  {
    id: "stackQueue",
    label: "STACK / QUEUE / ADT",
    domains: ["stackQueue"],
    x: -170,
    y: 335,
    rx: 300,
    ry: 205,
    rotate: 10,
    color: "#0085a8",
  },
  {
    id: "hashing",
    label: "HASHING / DIRECT ADDRESSING",
    domains: ["hashing"],
    x: 270,
    y: -360,
    rx: 285,
    ry: 205,
    rotate: -10,
    color: "#d9861f",
  },
  {
    id: "trees",
    label: "TREE / HEAP / AVL",
    domains: ["trees"],
    x: 520,
    y: -80,
    rx: 335,
    ry: 240,
    rotate: 8,
    color: "#7b54c8",
  },
  {
    id: "dp",
    label: "DP / HELPER TABLES",
    domains: ["dp"],
    x: 300,
    y: 330,
    rx: 315,
    ry: 215,
    rotate: -6,
    color: "#38a169",
  },
  {
    id: "graphs",
    label: "GRAPH / REACHABILITY",
    domains: ["graphs"],
    x: -30,
    y: 520,
    rx: 335,
    ry: 220,
    rotate: 0,
    color: "#5277d8",
  },
  {
    id: "weightedGraphs",
    label: "WEIGHTED GRAPH / RELAXATION",
    domains: ["weightedGraphs"],
    x: 430,
    y: 500,
    rx: 330,
    ry: 215,
    rotate: -14,
    color: "#5f3dc4",
  },
  {
    id: "proof",
    label: "PROOF / RUNTIME / INVARIANT",
    domains: ["proof"],
    x: 0,
    y: -40,
    rx: 370,
    ry: 225,
    rotate: 0,
    color: "#d6a500",
  },
];
