const semanticClusters = [
  {
    id: "arrays",
    label: "ARRAY / C / LOOP STATE",
    domains: ["arrays"],
    x: 0,
    y: -760,
    rx: 395,
    ry: 275,
    rotate: -2,
    color: "#6aa4ff",
  },
  {
    id: "sorting",
    label: "SORTING / EXCHANGE",
    domains: ["sorting"],
    x: -1080,
    y: -760,
    rx: 405,
    ry: 275,
    rotate: 4,
    color: "#d51f1f",
  },
  {
    id: "recursion",
    label: "RECURSION / DIVIDE",
    domains: ["recursion"],
    x: -1520,
    y: -700,
    rx: 340,
    ry: 245,
    rotate: -8,
    color: "#f06f9a",
  },
  {
    id: "pointers",
    label: "POINTERS / MEMORY",
    domains: ["pointers"],
    x: -1080,
    y: 0,
    rx: 390,
    ry: 275,
    rotate: -4,
    color: "#22a56a",
  },
  {
    id: "stackQueue",
    label: "STACK / QUEUE / ADT",
    domains: ["stackQueue"],
    x: -1200,
    y: 760,
    rx: 360,
    ry: 265,
    rotate: 5,
    color: "#0085a8",
  },
  {
    id: "hashing",
    label: "HASHING / DIRECT ADDRESSING",
    domains: ["hashing"],
    x: 1080,
    y: -760,
    rx: 395,
    ry: 275,
    rotate: -5,
    color: "#d9861f",
  },
  {
    id: "trees",
    label: "TREE / HEAP / AVL",
    domains: ["trees"],
    x: 1080,
    y: 0,
    rx: 410,
    ry: 285,
    rotate: 4,
    color: "#7b54c8",
  },
  {
    id: "dp",
    label: "DP / HELPER TABLES",
    domains: ["dp"],
    x: -400,
    y: 760,
    rx: 360,
    ry: 265,
    rotate: -3,
    color: "#38a169",
  },
  {
    id: "graphs",
    label: "GRAPH / REACHABILITY",
    domains: ["graphs"],
    x: 400,
    y: 760,
    rx: 360,
    ry: 265,
    rotate: 2,
    color: "#5277d8",
  },
  {
    id: "weightedGraphs",
    label: "WEIGHTED GRAPH / RELAXATION",
    domains: ["weightedGraphs"],
    x: 1200,
    y: 760,
    rx: 380,
    ry: 270,
    rotate: -5,
    color: "#5f3dc4",
  },
  {
    id: "proof",
    label: "PROOF / RUNTIME / INVARIANT",
    domains: ["proof"],
    x: 0,
    y: 0,
    rx: 405,
    ry: 285,
    rotate: 0,
    color: "#d6a500",
  },
];
