const concepts = [
  {
    id: "root",
    label: "INF II Semantic Exam Machine",
    kind: "core",
    domains: ["workflow", "proof"],
    taskTypes: ["runtime", "invariant", "writeC", "manualTrace"],
    summary:
      "A semantic learning graph for representation, mechanism, implementation, invariant, runtime and evidence.",
    priority: 3,
    anchor: { x: 0, y: 0 },
  },
  {
    id: "bubble",
    label: "Bubble Sort",
    kind: "algorithm",
    domains: ["sorting", "arrays"],
    mechanisms: ["adjacentComparison", "swap", "nestedloops"],
    representations: ["array"],
    proofPatterns: ["sortedSuffixInvariant"],
    taskTypes: ["writeC", "traceArray", "countComparisons", "runtime"],
    card: "bubble",
    sourceRefs: ["SL01", "Ex01"],
    summary: "Repeated adjacent compare-and-swap.",
    state: ["pass", "j", "unsorted prefix", "sorted suffix"],
    invariant: "After each pass, the largest remaining element is fixed.",
    runtime: "Theta(n^2) comparisons in the basic version.",
    edgeCases: ["n=0", "n=1", "already sorted", "reverse sorted"],
  },
  {
    id: "xsort",
    label: "XSort",
    kind: "algorithm",
    domains: ["sorting", "arrays"],
    mechanisms: ["swap", "boundaries", "bidirectional scan"],
    representations: ["array"],
    taskTypes: ["writeC", "traceArray", "manualTrace"],
    card: "xsort",
    sourceRefs: ["Ex01"],
    summary:
      "Bidirectional exchange sort pattern that combines boundary updates and swaps.",
  },
  {
    id: "heapSort",
    label: "HeapSort",
    kind: "algorithm",
    domains: ["sorting", "trees", "arrays"],
    mechanisms: ["swap", "heapify", "buildHeap"],
    representations: ["array", "heap"],
    proofPatterns: ["heapInvariant"],
    taskTypes: ["traceArray", "drawDataStructure", "runtime"],
    card: "heapSort",
    summary:
      "Array sorting by building a heap, swapping root with the end, and repairing downward.",
    state: ["heap size", "root", "last", "heapified prefix"],
    invariant: "Before each extraction, the active prefix is a valid heap.",
    runtime: "Theta(n log n) after linear-time BuildHeap.",
  },
  {
    id: "counting",
    label: "Counting Sort",
    kind: "algorithm",
    domains: ["sorting", "hashing", "arrays"],
    mechanisms: ["frequencyArray", "directAddressing", "scan"],
    representations: ["array", "frequency table"],
    taskTypes: ["writeC", "runtime", "edgeCase"],
    card: "counting",
    sourceRefs: ["FS25-Q-sortK"],
    summary:
      "Sort by counting occurrences in a direct-addressed frequency array.",
    runtime: "O(n + k), where k is the key range.",
  },
  {
    id: "kthLargestStack",
    label: "Kth Largest with Stack",
    kind: "examPattern",
    domains: ["stackQueue", "sorting"],
    mechanisms: ["stack", "selectionLogic", "auxiliaryStack", "adtRules"],
    representations: ["stack"],
    taskTypes: ["adtOnly", "pseudocode", "runtime"],
    card: "kthLargestStack",
    sourceRefs: ["FS24-Q6"],
    summary:
      "Selection under Stack ADT restrictions, using legal stack operations and auxiliary storage.",
    runtime:
      "Typically O(kn) or O(n log n)-style if a legal ordering strategy is used.",
  },
  {
    id: "selectionLogic",
    label: "selection logic",
    kind: "mechanism",
    domains: ["sorting", "proof"],
    taskTypes: ["runtime", "manualTrace"],
    summary:
      "Find an extremal or kth element by repeated scans, partitions, or restricted ADT passes.",
    anchor: { x: -140, y: -250 },
  },
  {
    id: "auxiliaryStack",
    label: "auxiliary stack",
    kind: "mechanism",
    domains: ["stackQueue", "pointers"],
    representations: ["stack"],
    taskTypes: ["adtOnly", "pseudocode"],
    summary:
      "Temporary stack used to preserve values while respecting legal ADT operations.",
    anchor: { x: -220, y: 250 },
  },
  {
    id: "stack",
    label: "Stack ADT",
    kind: "dataStructure",
    domains: ["stackQueue", "pointers"],
    mechanisms: ["push", "pop", "isEmpty"],
    representations: ["array", "linked list"],
    taskTypes: ["adtOnly", "writeC", "pseudocode"],
    card: "stack",
    summary:
      "Last-in-first-out ADT with restricted access through push and pop.",
    anchor: { x: -210, y: 330 },
  },
  {
    id: "queue",
    label: "Queue ADT",
    kind: "dataStructure",
    domains: ["stackQueue", "graphs"],
    mechanisms: ["enqueue", "dequeue"],
    representations: ["array", "linked list"],
    taskTypes: ["adtOnly", "pseudocode", "manualTrace"],
    card: "queue",
    summary: "First-in-first-out ADT that drives BFS-style layer traversal.",
    anchor: { x: -40, y: 390 },
  },
  {
    id: "bfs",
    label: "BFS",
    kind: "algorithm",
    domains: ["graphs", "stackQueue"],
    mechanisms: ["queue", "graphState", "visitedColor"],
    representations: ["graph"],
    proofPatterns: ["layerInvariant"],
    taskTypes: ["pseudocode", "manualTrace", "runtime"],
    card: "bfs",
    sourceRefs: ["Ex11"],
    summary: "Explore graph vertices by increasing unweighted distance layers.",
    state: ["queue", "color", "dist", "pred"],
    invariant:
      "When a vertex is dequeued, its shortest unweighted distance is known.",
    runtime: "O(V + E).",
  },
  {
    id: "dijkstra",
    label: "Dijkstra",
    kind: "algorithm",
    domains: ["weightedGraphs", "graphs"],
    mechanisms: ["relaxation", "priorityQueue", "graphState"],
    representations: ["weighted graph", "priority queue"],
    proofPatterns: ["greedyInvariant"],
    taskTypes: ["manualTrace", "runtime", "pseudocode"],
    card: "dijkstra",
    sourceRefs: ["FS24-Q-Dijkstra", "SL10"],
    summary:
      "Single-source shortest paths for nonnegative edge weights using extract-min and relaxation.",
    state: ["dist", "pred", "priority queue", "settled vertices"],
    invariant:
      "When a vertex is extracted, its shortest-path distance is final.",
    runtime: "Depends on priority queue representation.",
  },
  {
    id: "relaxation",
    label: "relaxation",
    kind: "mechanism",
    domains: ["weightedGraphs", "graphs"],
    taskTypes: ["manualTrace", "runtime"],
    summary:
      "Try to improve dist[v] through an edge (u,v) by comparing old and candidate distance.",
    anchor: { x: 330, y: 430 },
  },
  {
    id: "dpTemplate",
    label: "DP template",
    kind: "mechanism",
    domains: ["dp", "proof"],
    mechanisms: ["helperTable", "recurrence", "fillOrder"],
    taskTypes: ["fillHelperTable", "runtime", "invariant"],
    summary:
      "Define state meaning, recurrence, base cases, fill order, and reconstruction if needed.",
    anchor: { x: 260, y: 250 },
  },
  {
    id: "helperTable",
    label: "helper table",
    kind: "mechanism",
    domains: ["dp", "arrays"],
    representations: ["array", "matrix"],
    taskTypes: ["fillHelperTable", "writeC", "runtime"],
    summary:
      "Auxiliary array or matrix that stores solved subproblem values in DP.",
    anchor: { x: 220, y: 330 },
  },
  {
    id: "palCuts",
    label: "Palindrome Cuts DP",
    kind: "algorithm",
    domains: ["dp", "arrays"],
    mechanisms: ["helperTable", "recurrence", "fillOrder"],
    representations: ["string", "matrix"],
    taskTypes: ["fillHelperTable", "writeC", "runtime"],
    card: "palCuts",
    sourceRefs: ["Ex10"],
    summary:
      "Dynamic programming for minimum cuts using palindrome helper state and bottom-up loops.",
  },
  {
    id: "frequencyArray",
    label: "frequency array",
    kind: "mechanism",
    domains: ["hashing", "arrays", "sorting"],
    representations: ["array", "direct address table"],
    taskTypes: ["writeC", "runtime", "edgeCase"],
    summary:
      "Array indexed by key value to count occurrences or test direct-address membership.",
    anchor: { x: 170, y: -310 },
  },
  {
    id: "directAddressing",
    label: "direct addressing",
    kind: "representation",
    domains: ["hashing", "arrays"],
    representations: ["array"],
    taskTypes: ["writeC", "runtime", "edgeCase"],
    summary: "Use the key itself, or a shifted key, as an array slot address.",
    anchor: { x: 270, y: -300 },
  },
  {
    id: "swap",
    label: "swap / exchange",
    kind: "mechanism",
    domains: ["arrays", "sorting"],
    mechanisms: ["temporary variable"],
    representations: ["array"],
    taskTypes: ["writeC", "traceArray"],
    card: "swap",
    summary:
      "Exchange two values; central to bubble, selection, quick partition, heap sort and Sort3.",
    anchor: { x: -330, y: -340 },
  },
  {
    id: "heapify",
    label: "heapify",
    kind: "mechanism",
    domains: ["trees", "arrays", "sorting"],
    mechanisms: ["swap", "downwardRepair"],
    representations: ["array-as-tree", "heap"],
    taskTypes: ["manualTrace", "runtime", "drawDataStructure"],
    card: "heapify",
    summary:
      "Repair heap order by comparing a node with children and moving the violation downward.",
    anchor: { x: 310, y: -140 },
  },
  {
    id: "invariant",
    label: "invariant",
    kind: "proofPattern",
    domains: ["proof"],
    taskTypes: ["invariant", "runtime"],
    summary: "A maintained truth that connects algorithm state to correctness.",
    anchor: { x: 20, y: -130 },
  },
];
