const crossLinks = [
  // C and sorting mechanisms
  ["swap", "bubble", "swap"],
  ["swap", "selection", "swap"],
  ["swap", "quick", "swap"],
  ["swap", "heapSort", "swap"],
  ["swap", "sort3", "swap"],
  ["cStrings", "palRec", "strings"],
  ["cStrings", "lcs", "indices"],
  ["cStrings", "editDistance", "indices"],
  ["mallocFree", "dynamicArrays", "allocation"],
  ["dynamicArrays", "linked", "array→list"],

  // Hashing and direct addressing
  ["counting", "directAddressing", "frequency"],
  ["directAddressing", "hashing", "slot logic"],
  ["linked", "chaining", "chains"],
  ["chaining", "chainingOrder", "draw order"],
  ["linearProbe", "deleteHash", "repair"],
  ["linearProbe", "linearClustering", "clusters"],
  ["openAddress", "quadraticProbe", "probe formula"],

  // ADTs and traversal
  ["stack", "dfs", "DFS stack"],
  ["queue", "bfs", "BFS queue"],
  ["queue", "khop", "layers"],
  ["adtRules", "stackSort", "restriction"],
  ["adtRules", "reverseEven", "restriction"],
  ["adtRules", "kthLargestStack", "restriction"],
  ["stack", "twoStacksOneArray", "shared array"],
  ["queue", "stackTwoQueues", "simulate"],
  ["stack", "kthLargestStack", "scan max"],

  // Trees and heaps
  ["heap", "heapSort", "basis"],
  ["heapify", "heapSort", "basis"],
  ["heapify", "buildHeap", "bottom-up"],
  ["heap", "printHeap", "edges"],
  ["pointers", "linked", "basis"],
  ["pointers", "bst", "tree nodes"],
  ["pointers", "rotations", "pointers"],
  ["bst", "treeTraversal", "inorder sorted"],
  ["bst", "bstMinMax", "left/right"],
  ["bstDelete", "successor", "2-child case"],
  ["rotations", "avl", "restore"],
  ["rotations", "avlCases", "4 cases"],
  ["rotations", "redBlackHistorical", "historical"],

  // Proof and divide-and-conquer
  ["substitution", "maxSubarray", "proof"],
  ["master", "merge", "recurrence"],
  ["loopcount", "exactAnalysisWorkflow", "counts"],
  ["exactAnalysisWorkflow", "topKSelectionAnalysis", "algo1"],
  ["recursionTree", "asymmetricRecursionTree", "unbalanced"],
  ["invariant", "binarySearch", "interval"],
  ["invariant", "quick", "regions"],
  ["invariant", "sort3", "3 zones"],
  ["merge", "mergeHelper", "linear step"],
  ["quick", "quickPartition", "single pivot"],
  ["recursion", "hilbertRecurrence", "call order"],
  ["recursion", "binaryPrint", "call order"],
  ["recursion", "pyramid", "unwind"],

  // DP
  ["palRec", "palCuts", "recursion→DP"],
  ["matrix", "matrixPath", "helper table"],
  ["dpTemplate", "matrixChain", "interval DP"],
  ["dpTemplate", "lcs", "2D prefix"],
  ["dpTemplate", "coinChange", "1D DP"],
  ["dpTemplate", "dpRuntimeMemory", "cost"],
  ["solutionReconstruction", "lcsReconstruction", "backtrack"],
  ["solutionReconstruction", "matrixChainParens", "splits"],

  // Graph mechanisms
  ["matrix", "adjacency", "matrix repr"],
  ["adjacency", "adjacencyComplexity", "tradeoff"],
  ["dfs", "allPaths", "backtrack"],
  ["dfs", "cycle", "visited"],
  ["dfs", "topologicalSort", "finish time"],
  ["dfs", "dfsEdgeCode", "timestamps"],
  ["bfs", "bfsOrderNuance", "same dist"],
  ["queue", "shortestRootLeaf", "first leaf"],

  // Weighted graphs
  ["bfs", "dijkstra", "distance idea"],
  ["topologicalSort", "dagSSSP", "topo order"],
  ["relaxation", "bellmanFord", "core"],
  ["relaxation", "dijkstra", "core"],
  ["relaxation", "dagSSSP", "core"],
  ["relaxation", "bellmanFordTrace", "trace"],
  ["relaxation", "dijkstraTrace", "trace"],
  ["priorityQueue", "primJarnik", "extract-min"],
  ["priorityQueue", "dijkstra", "extract-min"],
  ["priorityQueue", "primTrace", "trace"],
  ["priorityQueue", "dijkstraTrace", "trace"],
  ["primJarnik", "dijkstra", "same queue shape"],
  ["primJarnik", "primTrace", "trace"],
  ["mst", "mstAssumptions", "assumptions"],
  ["dijkstra", "dijkstraAssumptions", "nonnegative"],
  ["dijkstra", "dijkstraTrace", "distance changes"],
  ["bellmanFord", "bellmanFordDetails", "details"],
  ["bellmanFord", "bellmanFordTrace", "passes"],
  ["negativeCycle", "bellmanFord", "detect"],
  ["arbitrage", "negativeCycle", "log transform"],
  ["arbitrage", "arbitrageTransform", "-log(rate)"],

  // Exam traps
  ["traceOutput", "backwardRunLength", "run trace"],
];
