const relations = [
  {
    source: "bubble",
    target: "swap",
    type: "usesMechanism",
    weight: 0.95,
    label: "adjacent exchange",
    evidence: ["SL01", "Ex01"],
  },
  {
    source: "bubble",
    target: "nestedloops",
    type: "usesMechanism",
    weight: 0.85,
    label: "double loop",
    evidence: ["Ex01"],
  },
  {
    source: "bubble",
    target: "xsort",
    type: "implementationSimilarity",
    weight: 0.78,
    label: "exchange sort",
    evidence: ["Ex01"],
  },
  {
    source: "bubble",
    target: "selection",
    type: "sameStatePattern",
    weight: 0.62,
    label: "fixed suffix/prefix",
  },
  {
    source: "heapSort",
    target: "heapify",
    type: "usesMechanism",
    weight: 0.96,
    label: "downward repair",
  },
  {
    source: "heapSort",
    target: "swap",
    type: "usesMechanism",
    weight: 0.75,
    label: "root/last exchange",
  },
  {
    source: "heapSort",
    target: "buildHeap",
    type: "prerequisite",
    weight: 0.82,
    label: "heap construction",
  },
  {
    source: "heapify",
    target: "priorityQueue",
    type: "sameRepresentation",
    weight: 0.55,
    label: "heap logic",
  },
  {
    source: "counting",
    target: "frequencyArray",
    type: "usesMechanism",
    weight: 0.95,
    label: "counts",
    evidence: ["FS25-Q-sortK"],
  },
  {
    source: "frequencyArray",
    target: "directAddressing",
    type: "sameRepresentation",
    weight: 0.9,
    label: "slot by key",
    evidence: ["FS25-Q-sortK"],
  },
  {
    source: "counting",
    target: "hashing",
    type: "sameRepresentation",
    weight: 0.58,
    label: "table indexing",
    evidence: ["FS25-Q-sortK"],
  },
  {
    source: "kthLargestStack",
    target: "stack",
    type: "usesMechanism",
    weight: 0.94,
    label: "legal stack ops",
    evidence: ["FS24-Q6"],
  },
  {
    source: "kthLargestStack",
    target: "selectionLogic",
    type: "sameStatePattern",
    weight: 0.84,
    label: "kth/extreme selection",
    evidence: ["FS24-Q6"],
  },
  {
    source: "kthLargestStack",
    target: "auxiliaryStack",
    type: "usesMechanism",
    weight: 0.9,
    label: "temporary stack",
    evidence: ["FS24-Q6"],
  },
  {
    source: "stack",
    target: "adtRules",
    type: "prerequisite",
    weight: 0.82,
    label: "operation restriction",
    evidence: ["FS24-Q6"],
  },
  {
    source: "bfs",
    target: "queue",
    type: "usesMechanism",
    weight: 0.96,
    label: "layer queue",
    evidence: ["Ex11"],
  },
  {
    source: "bfs",
    target: "dijkstra",
    type: "sameStatePattern",
    weight: 0.68,
    label: "distance state",
  },
  {
    source: "dijkstra",
    target: "relaxation",
    type: "usesMechanism",
    weight: 0.96,
    label: "edge update",
    evidence: ["FS24-Q-Dijkstra"],
  },
  {
    source: "dijkstra",
    target: "priorityQueue",
    type: "usesMechanism",
    weight: 0.85,
    label: "extract-min",
    evidence: ["SL10"],
  },
  {
    source: "relaxation",
    target: "bellmanFord",
    type: "usesMechanism",
    weight: 0.9,
    label: "all edges",
  },
  {
    source: "relaxation",
    target: "dagSSSP",
    type: "usesMechanism",
    weight: 0.82,
    label: "topo order",
  },
  {
    source: "relaxation",
    target: "negativeCycle",
    type: "sameStatePattern",
    weight: 0.68,
    label: "detect improvement",
  },
  {
    source: "negativeCycle",
    target: "arbitrage",
    type: "sameProofPattern",
    weight: 0.72,
    label: "log transform",
  },
  {
    source: "dpTemplate",
    target: "helperTable",
    type: "usesMechanism",
    weight: 0.95,
    label: "subproblem memory",
    evidence: ["Ex10"],
  },
  {
    source: "palCuts",
    target: "helperTable",
    type: "usesMechanism",
    weight: 0.92,
    label: "palindrome table",
    evidence: ["Ex10"],
  },
  {
    source: "palCuts",
    target: "dpTemplate",
    type: "sameStatePattern",
    weight: 0.9,
    label: "recurrence + fill",
    evidence: ["Ex10"],
  },
  {
    source: "helperTable",
    target: "matrix",
    type: "sameRepresentation",
    weight: 0.72,
    label: "2D state",
    evidence: ["Ex10"],
  },
  {
    source: "binarySearch",
    target: "invariant",
    type: "sameProofPattern",
    weight: 0.72,
    label: "interval invariant",
  },
  {
    source: "quick",
    target: "invariant",
    type: "sameProofPattern",
    weight: 0.7,
    label: "partition invariant",
  },
  {
    source: "bst",
    target: "heap",
    type: "contrast",
    weight: 0.72,
    label: "ordered tree vs heap order",
  },
  {
    source: "linearSearchVariants",
    target: "scan",
    type: "usesMechanism",
    weight: 0.9,
    label: "one pass",
    evidence: ["SL01", "Ex00"],
  },
  {
    source: "algorithmProgramDataStructure",
    target: "inputOutputSpec",
    type: "prerequisite",
    weight: 0.72,
    label: "problem specification",
    evidence: ["SL01"],
  },
  {
    source: "outOfBoundsWhile",
    target: "boundaries",
    type: "taskPattern",
    weight: 0.78,
    label: "guard before read",
    evidence: ["SL01"],
  },
  {
    source: "secondLargest",
    target: "scan",
    type: "usesMechanism",
    weight: 0.82,
    label: "one-pass state",
    evidence: ["Ex00"],
  },
  {
    source: "diagonalSum",
    target: "matrix",
    type: "sameRepresentation",
    weight: 0.82,
    label: "A[i][i]",
    evidence: ["Ex00"],
  },
  {
    source: "linearVsBinarySearch",
    target: "binarySearch",
    type: "contrast",
    weight: 0.85,
    label: "sorted precondition",
    evidence: ["SL02", "Ex03"],
  },
  {
    source: "countOccurrenceSorted",
    target: "binarySearch",
    type: "usesMechanism",
    weight: 0.82,
    label: "search sorted A2",
    evidence: ["Ex03"],
  },
  {
    source: "daryHeapIndexing",
    target: "daryHeap",
    type: "usesMechanism",
    weight: 0.82,
    label: "child formulas",
    evidence: ["SL04", "Ex05"],
  },
  {
    source: "pointerPrintAddresses",
    target: "pointers",
    type: "sameStatePattern",
    weight: 0.82,
    label: "address state",
    evidence: ["SL05", "Ex06"],
  },
  {
    source: "arrayAssignmentInvalid",
    target: "arrayDecay",
    type: "contrast",
    weight: 0.82,
    label: "array vs pointer assignment",
    evidence: ["SL05", "Ex06"],
  },
  {
    source: "dynamicReversePrependOwnership",
    target: "dynamicArrays",
    type: "usesMechanism",
    weight: 0.82,
    label: "malloc ownership",
    evidence: ["Ex06"],
  },
  {
    source: "stackOperationSequence",
    target: "stack",
    type: "taskPattern",
    weight: 0.8,
    label: "LIFO trace",
    evidence: ["Ex07"],
  },
  {
    source: "queueOperationSequence",
    target: "queue",
    type: "taskPattern",
    weight: 0.8,
    label: "FIFO trace",
    evidence: ["Ex07"],
  },
  {
    source: "arrayStackImplementation",
    target: "stack",
    type: "sameRepresentation",
    weight: 0.78,
    label: "array top",
    evidence: ["Ex07"],
  },
  {
    source: "arrayCircularQueueImplementation",
    target: "queue",
    type: "sameRepresentation",
    weight: 0.78,
    label: "front/rear",
    evidence: ["Ex07"],
  },
  {
    source: "binaryTreeTraps",
    target: "binaryTree",
    type: "taskPattern",
    weight: 0.82,
    label: "true/false",
    evidence: ["SL06", "Ex08"],
  },
  {
    source: "bstInsertDoublePointer",
    target: "bstInsert",
    type: "usesMechanism",
    weight: 0.8,
    label: "root may change",
    evidence: ["Ex08"],
  },
  {
    source: "graphTerminologyTraps",
    target: "graphTerminology",
    type: "taskPattern",
    weight: 0.82,
    label: "definition traps",
    evidence: ["SL09"],
  },
  {
    source: "undirectedCycleDetection",
    target: "cycle",
    type: "usesMechanism",
    weight: 0.84,
    label: "ignore parent",
    evidence: ["Ex11"],
  },
  {
    source: "kHopExact",
    target: "khop",
    type: "taskPattern",
    weight: 0.84,
    label: "exact distance",
    evidence: ["Ex11"],
  },
  {
    source: "weightedGraphDefinition",
    target: "weightedGraph",
    type: "sameRepresentation",
    weight: 0.78,
    label: "weight function",
    evidence: ["SL10"],
  },
  {
    source: "mstVsSssp",
    target: "mst",
    type: "contrast",
    weight: 0.82,
    label: "tree objective",
    evidence: ["SL10"],
  },
  {
    source: "mstVsSssp",
    target: "sssp",
    type: "contrast",
    weight: 0.82,
    label: "distance objective",
    evidence: ["SL10"],
  },
  {
    source: "spanningTree",
    target: "mst",
    type: "prerequisite",
    weight: 0.78,
    label: "tree properties",
    evidence: ["SL10"],
  },
  {
    source: "safeEdge",
    target: "cutLightEdge",
    type: "sameProofPattern",
    weight: 0.82,
    label: "safe MST extension",
    evidence: ["SL10"],
  },
  {
    source: "cutLightEdgeProof",
    target: "cutLightEdge",
    type: "sameProofPattern",
    weight: 0.86,
    label: "exchange proof",
    evidence: ["SL10"],
  },
  {
    source: "minimumEdgeMstProof",
    target: "cutLightEdgeProof",
    type: "sameProofPattern",
    weight: 0.78,
    label: "minimum edge exchange",
    evidence: ["SL10"],
  },
  {
    source: "arrayInitialization",
    target: "frequencyArray",
    type: "usesMechanism",
    weight: 0.76,
    label: "zero counts",
    evidence: ["FS25-sortK-frequency-array"],
  },
];
