const relations = [
  {
    source: "bubble",
    target: "swap",
    type: "usesMechanism",
    weight: 0.95,
    label: "adjacent exchange",
    evidence: ["SL01", "Ex01"],
  },
  {
    source: "bubble",
    target: "nestedloops",
    type: "usesMechanism",
    weight: 0.85,
    label: "double loop",
    evidence: ["Ex01"],
  },
  {
    source: "bubble",
    target: "xsort",
    type: "implementationSimilarity",
    weight: 0.78,
    label: "exchange sort",
    evidence: ["Ex01"],
  },
  {
    source: "bubble",
    target: "selection",
    type: "sameStatePattern",
    weight: 0.62,
    label: "fixed suffix/prefix",
  },
  {
    source: "heapSort",
    target: "heapify",
    type: "usesMechanism",
    weight: 0.96,
    label: "downward repair",
  },
  {
    source: "heapSort",
    target: "swap",
    type: "usesMechanism",
    weight: 0.75,
    label: "root/last exchange",
  },
  {
    source: "heapSort",
    target: "buildHeap",
    type: "prerequisite",
    weight: 0.82,
    label: "heap construction",
  },
  {
    source: "heapify",
    target: "priorityQueue",
    type: "sameRepresentation",
    weight: 0.55,
    label: "heap logic",
  },
  {
    source: "counting",
    target: "frequencyArray",
    type: "usesMechanism",
    weight: 0.95,
    label: "counts",
    evidence: ["FS25-Q-sortK"],
  },
  {
    source: "frequencyArray",
    target: "directAddressing",
    type: "sameRepresentation",
    weight: 0.9,
    label: "slot by key",
    evidence: ["FS25-Q-sortK"],
  },
  {
    source: "counting",
    target: "hashing",
    type: "sameRepresentation",
    weight: 0.58,
    label: "table indexing",
    evidence: ["FS25-Q-sortK"],
  },
  {
    source: "kthLargestStack",
    target: "stack",
    type: "usesMechanism",
    weight: 0.94,
    label: "legal stack ops",
    evidence: ["FS24-Q6"],
  },
  {
    source: "kthLargestStack",
    target: "selectionLogic",
    type: "sameStatePattern",
    weight: 0.84,
    label: "kth/extreme selection",
    evidence: ["FS24-Q6"],
  },
  {
    source: "kthLargestStack",
    target: "auxiliaryStack",
    type: "usesMechanism",
    weight: 0.9,
    label: "temporary stack",
    evidence: ["FS24-Q6"],
  },
  {
    source: "stack",
    target: "adtRules",
    type: "prerequisite",
    weight: 0.82,
    label: "operation restriction",
    evidence: ["FS24-Q6"],
  },
  {
    source: "bfs",
    target: "queue",
    type: "usesMechanism",
    weight: 0.96,
    label: "layer queue",
    evidence: ["Ex11"],
  },
  {
    source: "bfs",
    target: "dijkstra",
    type: "sameStatePattern",
    weight: 0.68,
    label: "distance state",
  },
  {
    source: "dijkstra",
    target: "relaxation",
    type: "usesMechanism",
    weight: 0.96,
    label: "edge update",
    evidence: ["FS24-Q-Dijkstra"],
  },
  {
    source: "dijkstra",
    target: "priorityQueue",
    type: "usesMechanism",
    weight: 0.85,
    label: "extract-min",
    evidence: ["SL10"],
  },
  {
    source: "relaxation",
    target: "bellmanFord",
    type: "usesMechanism",
    weight: 0.9,
    label: "all edges",
  },
  {
    source: "relaxation",
    target: "dagSSSP",
    type: "usesMechanism",
    weight: 0.82,
    label: "topo order",
  },
  {
    source: "relaxation",
    target: "negativeCycle",
    type: "sameStatePattern",
    weight: 0.68,
    label: "detect improvement",
  },
  {
    source: "negativeCycle",
    target: "arbitrage",
    type: "sameProofPattern",
    weight: 0.72,
    label: "log transform",
  },
  {
    source: "dpTemplate",
    target: "helperTable",
    type: "usesMechanism",
    weight: 0.95,
    label: "subproblem memory",
    evidence: ["Ex10"],
  },
  {
    source: "palCuts",
    target: "helperTable",
    type: "usesMechanism",
    weight: 0.92,
    label: "palindrome table",
    evidence: ["Ex10"],
  },
  {
    source: "palCuts",
    target: "dpTemplate",
    type: "sameStatePattern",
    weight: 0.9,
    label: "recurrence + fill",
    evidence: ["Ex10"],
  },
  {
    source: "helperTable",
    target: "matrix",
    type: "sameRepresentation",
    weight: 0.72,
    label: "2D state",
    evidence: ["Ex10"],
  },
  {
    source: "binarySearch",
    target: "invariant",
    type: "sameProofPattern",
    weight: 0.72,
    label: "interval invariant",
  },
  {
    source: "quick",
    target: "invariant",
    type: "sameProofPattern",
    weight: 0.7,
    label: "partition invariant",
  },
  {
    source: "bst",
    target: "heap",
    type: "contrast",
    weight: 0.72,
    label: "ordered tree vs heap order",
  },
];
