const sources = [
  {
    id: "SL01",
    type: "lecture",
    title: "Sorting and C array mechanisms",
    weight: 0.8,
    concepts: ["bubble", "selection", "swap", "nestedloops", "invariant"],
    taskTypes: ["writeC", "traceArray", "runtime", "invariant"],
    strengthens: [
      ["bubble", "swap", "usesMechanism", 0.9],
      ["selection", "swap", "usesMechanism", 0.75],
      ["bubble", "invariant", "sameProofPattern", 0.7],
    ],
  },
  {
    id: "Ex01",
    type: "exercise",
    title: "Sorting traces, XSort and array C patterns",
    weight: 1,
    concepts: ["bubble", "xsort", "swap", "boundaries", "pairSum", "matrix"],
    taskTypes: ["writeC", "traceArray", "countComparisons"],
    strengthens: [
      ["bubble", "xsort", "implementationSimilarity", 0.8],
      ["xsort", "boundaries", "usesMechanism", 0.86],
      ["pairSum", "nestedloops", "usesMechanism", 0.75],
    ],
  },
  {
    id: "FS24-Q1",
    type: "pastExam",
    title: "Backward run-length tracing",
    weight: 0.75,
    concepts: ["scan", "boundaries", "arrayDecay"],
    taskTypes: ["traceOutput", "manualTrace", "edgeCase"],
    strengthens: [
      ["scan", "boundaries", "sameStatePattern", 0.75],
      ["scan", "arrayDecay", "implementationSimilarity", 0.45],
    ],
  },
  {
    id: "FS24-Q6",
    type: "pastExam",
    title: "Kth largest using only Stack ADT",
    weight: 0.9,
    concepts: [
      "stack",
      "adtRules",
      "kthLargestStack",
      "selectionLogic",
      "auxiliaryStack",
      "topKSelectionAnalysis",
    ],
    taskTypes: ["adtOnly", "runtime", "pseudocode"],
    strengthens: [
      ["stack", "adtRules", "examCooccurrence", 0.9],
      ["kthLargestStack", "selectionLogic", "sameStatePattern", 0.85],
      ["kthLargestStack", "auxiliaryStack", "usesMechanism", 0.9],
      ["selectionLogic", "topKSelectionAnalysis", "sameStatePattern", 0.65],
    ],
  },
  {
    id: "FS25-Q-sortK",
    type: "pastExam",
    title: "Frequency/direct-address sorting",
    weight: 0.85,
    concepts: [
      "counting",
      "frequencyArray",
      "directAddressing",
      "hashing",
      "arrayInitialization",
    ],
    taskTypes: ["writeC", "runtime", "edgeCase"],
    strengthens: [
      ["counting", "frequencyArray", "usesMechanism", 0.95],
      ["frequencyArray", "directAddressing", "sameRepresentation", 0.9],
      ["counting", "hashing", "examCooccurrence", 0.75],
    ],
  },
  {
    id: "Ex10",
    type: "exercise",
    title: "Dynamic programming helper tables",
    weight: 1,
    concepts: [
      "dpTemplate",
      "helperTable",
      "matrix",
      "palCuts",
      "matrixPath",
      "lcs",
      "editDistance",
    ],
    taskTypes: ["fillHelperTable", "writeC", "runtime", "recurrence"],
    strengthens: [
      ["dpTemplate", "helperTable", "usesMechanism", 0.95],
      ["helperTable", "matrix", "sameRepresentation", 0.75],
      ["palCuts", "dpTemplate", "sameStatePattern", 0.9],
      ["lcs", "editDistance", "sameStatePattern", 0.74],
    ],
  },
  {
    id: "Ex11",
    type: "exercise",
    title: "Graph traversal and k-hop reasoning",
    weight: 0.95,
    concepts: ["bfs", "dfs", "queue", "stack", "khop", "graphState"],
    taskTypes: ["pseudocode", "manualTrace", "runtime"],
    strengthens: [
      ["bfs", "queue", "usesMechanism", 0.96],
      ["dfs", "stack", "usesMechanism", 0.78],
      ["bfs", "khop", "sameStatePattern", 0.86],
    ],
  },
  {
    id: "FS24-Q-Dijkstra",
    type: "pastExam",
    title: "Dijkstra relaxation changes",
    weight: 0.85,
    concepts: [
      "dijkstra",
      "relaxation",
      "priorityQueue",
      "dijkstraTrace",
      "graphState",
    ],
    taskTypes: ["manualTrace", "runtime", "pseudocode"],
    strengthens: [
      ["dijkstra", "relaxation", "usesMechanism", 0.96],
      ["dijkstra", "priorityQueue", "usesMechanism", 0.8],
      ["relaxation", "dijkstraTrace", "taskPattern", 0.85],
    ],
  },
  {
    id: "SL10",
    type: "lecture",
    title: "Weighted graph algorithms",
    weight: 0.8,
    concepts: [
      "relaxation",
      "dijkstra",
      "bellmanFord",
      "dagSSSP",
      "negativeCycle",
      "arbitrage",
      "primJarnik",
    ],
    taskTypes: ["manualTrace", "runtime", "pseudocode"],
    strengthens: [
      ["relaxation", "bellmanFord", "usesMechanism", 0.9],
      ["relaxation", "dagSSSP", "usesMechanism", 0.82],
      ["negativeCycle", "arbitrage", "sameProofPattern", 0.82],
      ["primJarnik", "dijkstra", "sameStatePattern", 0.68],
    ],
  },
];
