const sources = [
  {
    id: "SL01",
    type: "lecture",
    title: "Specification, C arrays, search and early loop reasoning",
    weight: 0.8,
    concepts: [
      "algorithmProgramDataStructure",
      "inputOutputSpec",
      "ambiguousSearchOutput",
      "linearSearchVariants",
      "outOfBoundsWhile",
      "scan",
      "matrix",
      "sieve",
      "boundaries",
      "invariant",
    ],
    taskTypes: ["writeC", "traceArray", "runtime", "edgeCase"],
    strengthens: [
      ["inputOutputSpec", "ambiguousSearchOutput", "sameProofPattern", 0.82],
      ["linearSearchVariants", "scan", "usesMechanism", 0.9],
      ["sieve", "boundaries", "usesMechanism", 0.78],
    ],
  },
  {
    id: "SL02",
    type: "lecture",
    title: "Search, sorting costs, invariants and growth",
    weight: 0.8,
    concepts: [
      "linearVsBinarySearch",
      "binarySearch",
      "insertion",
      "binaryInsertionSortNuance",
      "functionGrowthRanking",
      "loopcount",
      "exactAnalysisWorkflow",
      "invariant",
      "bigO",
      "bestWorstAvg",
    ],
    taskTypes: ["runtime", "invariant", "manualTrace", "edgeCase"],
    strengthens: [
      ["binarySearch", "invariant", "sameProofPattern", 0.82],
      ["insertion", "binaryInsertionSortNuance", "contrast", 0.8],
      ["loopcount", "exactAnalysisWorkflow", "usesMechanism", 0.86],
    ],
  },
  {
    id: "SL03",
    type: "lecture",
    title: "Divide and conquer and recurrence solving",
    weight: 0.8,
    concepts: [
      "recurrences",
      "recursionTree",
      "substitution",
      "master",
      "masterWorksheet",
      "backwardSubstitution",
      "asymmetricRecursionTree",
      "maxSubarray",
      "merge",
      "mergeHelper",
    ],
    taskTypes: ["recurrence", "runtime", "pseudocode"],
    strengthens: [
      ["recurrences", "recursionTree", "usesMechanism", 0.8],
      ["master", "masterWorksheet", "usesMechanism", 0.86],
      ["maxSubarray", "backwardSubstitution", "sameProofPattern", 0.72],
    ],
  },
  {
    id: "SL04",
    type: "lecture",
    title: "Heaps, priority queues and quicksort partitioning",
    weight: 0.8,
    concepts: [
      "heap",
      "heapify",
      "buildHeap",
      "heapSort",
      "heapTraceTable",
      "priorityQueue",
      "daryHeap",
      "daryHeapIndexing",
      "quick",
      "quicksortAssumptions",
    ],
    taskTypes: ["manualTrace", "drawDataStructure", "runtime"],
    strengthens: [
      ["heapSort", "heapify", "usesMechanism", 0.95],
      ["heapify", "buildHeap", "usesMechanism", 0.82],
      ["quick", "quicksortAssumptions", "sameProofPattern", 0.78],
    ],
  },
  {
    id: "SL05",
    type: "lecture",
    title: "Pointers, dynamic memory and linked structures",
    weight: 0.8,
    concepts: [
      "pointers",
      "arrayDecay",
      "mallocFree",
      "pointerPrintAddresses",
      "cPassByValue",
      "arrayAssignmentInvalid",
      "pointerOffsetSwap",
      "dynamicArrays",
      "linked",
      "linkedListRearrangementTrace",
    ],
    taskTypes: ["writeC", "traceOutput", "manualTrace", "edgeCase"],
    strengthens: [
      ["pointers", "arrayDecay", "sameRepresentation", 0.86],
      ["mallocFree", "dynamicArrays", "usesMechanism", 0.84],
      ["linked", "linkedListRearrangementTrace", "taskPattern", 0.82],
    ],
  },
  {
    id: "SL06",
    type: "lecture",
    title: "Dictionaries, trees, BSTs, expression trees and AVL",
    weight: 0.8,
    concepts: [
      "dictionary",
      "binaryTree",
      "binaryTreeTraps",
      "expressionTree",
      "treeTraversal",
      "bst",
      "bstMinMax",
      "successor",
      "bstVsHeap",
      "avl",
      "rotations",
    ],
    taskTypes: ["drawDataStructure", "manualTrace", "pseudocode", "runtime"],
    strengthens: [
      ["dictionary", "bst", "sameRepresentation", 0.78],
      ["bst", "bstMinMax", "usesMechanism", 0.82],
      ["rotations", "avl", "usesMechanism", 0.92],
    ],
  },
  {
    id: "SL07",
    type: "lecture",
    title: "Hashing, probing, deletion and resizing",
    weight: 0.8,
    concepts: [
      "hashing",
      "hashFunction",
      "chaining",
      "loadFactor",
      "openAddress",
      "linearProbe",
      "linearClustering",
      "quadraticProbe",
      "doubleHash",
      "tombstoneRepair",
      "deleteHash",
    ],
    taskTypes: ["manualTrace", "writeC", "runtime", "edgeCase"],
    strengthens: [
      ["openAddress", "linearProbe", "usesMechanism", 0.84],
      ["openAddress", "quadraticProbe", "usesMechanism", 0.78],
      ["deleteHash", "tombstoneRepair", "contrast", 0.8],
    ],
  },
  {
    id: "SL08",
    type: "lecture",
    title: "Dynamic programming templates and reconstruction",
    weight: 0.8,
    concepts: [
      "dpTemplate",
      "memoization",
      "helperTable",
      "matrixChain",
      "matrixChainParens",
      "lcs",
      "lcsReconstruction",
      "coinChange",
      "solutionReconstruction",
      "dpRuntimeMemory",
    ],
    taskTypes: ["fillHelperTable", "recurrence", "runtime", "pseudocode"],
    strengthens: [
      ["dpTemplate", "helperTable", "usesMechanism", 0.95],
      ["matrixChain", "matrixChainParens", "taskPattern", 0.86],
      ["lcs", "lcsReconstruction", "taskPattern", 0.86],
    ],
  },
  {
    id: "SL09",
    type: "lecture",
    title: "Graph representation, BFS, DFS and path reasoning",
    weight: 0.8,
    concepts: [
      "graphTerminology",
      "graphTerminologyTraps",
      "adjacency",
      "adjacencyComplexity",
      "graphState",
      "bfs",
      "possibleBfsSequence",
      "dfs",
      "possibleDfsSequence",
      "cycle",
      "allPaths",
      "khop",
    ],
    taskTypes: ["pseudocode", "manualTrace", "runtime"],
    strengthens: [
      ["adjacency", "adjacencyComplexity", "sameRepresentation", 0.9],
      ["bfs", "possibleBfsSequence", "taskPattern", 0.82],
      ["dfs", "possibleDfsSequence", "taskPattern", 0.82],
    ],
  },
  {
    id: "SL10",
    type: "lecture",
    title: "Weighted graph algorithms",
    weight: 0.8,
    concepts: [
      "weightedGraph",
      "weightedGraphDefinition",
      "mst",
      "mstVsSssp",
      "spanningTree",
      "safeEdge",
      "cutLightEdge",
      "cutLightEdgeProof",
      "minimumEdgeMstProof",
      "primJarnik",
      "primTrace",
      "relaxation",
      "bellmanFord",
      "bellmanFordTrace",
      "dagSSSP",
      "dijkstra",
      "dijkstraTrace",
      "negativeCycle",
      "arbitrageTransform",
    ],
    taskTypes: ["manualTrace", "runtime", "pseudocode"],
    strengthens: [
      ["primJarnik", "primTrace", "taskPattern", 0.92],
      ["relaxation", "bellmanFord", "usesMechanism", 0.9],
      ["relaxation", "dagSSSP", "usesMechanism", 0.82],
      ["negativeCycle", "arbitrageTransform", "sameProofPattern", 0.82],
    ],
  },
  {
    id: "Ex00",
    type: "exercise",
    title: "C compile/run, linear search, second largest and diagonal sum",
    weight: 1,
    concepts: [
      "compileRunC",
      "linearSearchVariants",
      "scan",
      "secondLargest",
      "matrix",
      "diagonalSum",
      "boundaries",
      "edgeCases",
    ],
    taskTypes: ["writeC", "traceOutput", "traceArray", "runtime"],
    strengthens: [
      ["compileRunC", "traceOutput", "taskPattern", 0.72],
      ["linearSearchVariants", "scan", "usesMechanism", 0.92],
      ["diagonalSum", "matrix", "sameRepresentation", 0.85],
    ],
  },
  {
    id: "Ex01",
    type: "exercise",
    title: "Sorting traces, XSort, Hilbert length and array C patterns",
    weight: 1,
    concepts: [
      "bubble",
      "xsort",
      "swap",
      "boundaries",
      "pairSum",
      "matrix",
      "hilbertDrawingRecursion",
      "hilbertLengthRecurrence",
    ],
    taskTypes: ["writeC", "traceArray", "countComparisons", "recurrence"],
    strengthens: [
      ["bubble", "xsort", "implementationSimilarity", 0.8],
      ["xsort", "boundaries", "usesMechanism", 0.86],
      ["hilbertDrawingRecursion", "hilbertLengthRecurrence", "contrast", 0.86],
    ],
  },
  {
    id: "Ex02",
    type: "exercise",
    title: "Recursive output, strings, binary print and Hanoi",
    weight: 0.9,
    concepts: [
      "recursion",
      "palRec",
      "binaryPrint",
      "hanoi",
      "pyramid",
      "cStrings",
      "edgeCases",
    ],
    taskTypes: ["traceOutput", "writeC", "recurrence", "edgeCase"],
    strengthens: [
      ["recursion", "binaryPrint", "taskPattern", 0.78],
      ["recursion", "hanoi", "taskPattern", 0.76],
      ["cStrings", "palRec", "sameRepresentation", 0.72],
    ],
  },
  {
    id: "Ex03",
    type: "exercise",
    title: "Exact analysis, binary search, invariants and top-k algo1",
    weight: 1,
    concepts: [
      "linearVsBinarySearch",
      "binarySearch",
      "binaryInsertionSortNuance",
      "countOccurrenceSorted",
      "functionGrowthRanking",
      "coupledLoopSum",
      "exactAnalysisWorkflow",
      "topKSelectionAnalysis",
      "invariant",
      "edgeCases",
    ],
    taskTypes: ["runtime", "invariant", "pseudocode", "edgeCase"],
    strengthens: [
      ["binarySearch", "linearVsBinarySearch", "contrast", 0.9],
      ["coupledLoopSum", "exactAnalysisWorkflow", "usesMechanism", 0.88],
      ["topKSelectionAnalysis", "invariant", "sameProofPattern", 0.86],
    ],
  },
  {
    id: "Ex04",
    type: "exercise",
    title: "Divide and conquer, recurrence proofs and dynamic arrays",
    weight: 1,
    concepts: [
      "binarySearch",
      "maxSubarray",
      "taRecurrence",
      "substitution",
      "backwardSubstitution",
      "asymmetricRecursionTree",
      "masterWorksheet",
      "dynamicArrayGrowth",
      "amortized",
    ],
    taskTypes: ["recurrence", "runtime", "pseudocode"],
    strengthens: [
      ["maxSubarray", "recurrences", "usesMechanism", 0.84],
      ["taRecurrence", "substitution", "sameProofPattern", 0.86],
      ["dynamicArrayGrowth", "amortized", "sameProofPattern", 0.82],
    ],
  },
  {
    id: "Ex05",
    type: "exercise",
    title: "Heapsort trace, d-ary heap helpers and dual-pivot quicksort",
    weight: 1,
    concepts: [
      "heapSort",
      "heapTraceTable",
      "buildHeapExchangeCount",
      "buildHeap",
      "heapify",
      "daryHeap",
      "daryHeapIndexing",
      "printHeap",
      "dualPivotTrace",
      "quick",
      "quicksortAssumptions",
    ],
    taskTypes: ["manualTrace", "drawDataStructure", "writeC", "runtime"],
    strengthens: [
      ["heapTraceTable", "heapSort", "taskPattern", 0.95],
      ["buildHeapExchangeCount", "buildHeap", "taskPattern", 0.9],
      ["dualPivotTrace", "quick", "taskPattern", 0.92],
    ],
  },
  {
    id: "Ex06",
    type: "exercise",
    title: "Pointer values, malloc, array decay and linked-list conversion",
    weight: 1,
    concepts: [
      "pointerPrintAddresses",
      "mallocCopyFree",
      "cPassByValue",
      "arrayAssignmentInvalid",
      "arrayDecay",
      "pointerOffsetSwap",
      "dynamicReversePrependOwnership",
      "dynamicArrays",
      "arrayToLinkedList",
      "linkedListRearrangementTrace",
    ],
    taskTypes: ["writeC", "traceOutput", "manualTrace", "edgeCase"],
    strengthens: [
      ["cPassByValue", "pointerOffsetSwap", "sameStatePattern", 0.82],
      ["mallocCopyFree", "mallocFree", "usesMechanism", 0.9],
      ["arrayToLinkedList", "linked", "sameRepresentation", 0.86],
    ],
  },
  {
    id: "Ex07",
    type: "exercise",
    title: "Stack and queue ADT implementations and transformations",
    weight: 1,
    concepts: [
      "stackOperationSequence",
      "queueOperationSequence",
      "twoStacksOneArray",
      "queueTwoStacks",
      "stackTwoQueues",
      "arrayStackImplementation",
      "arrayCircularQueueImplementation",
      "stackLinkedList",
      "queueLinkedList",
      "reverseEven",
      "adtRules",
    ],
    taskTypes: ["adtOnly", "pseudocode", "writeC", "manualTrace"],
    strengthens: [
      ["queueTwoStacks", "stack", "usesMechanism", 0.84],
      ["stackTwoQueues", "queue", "usesMechanism", 0.84],
      ["reverseEven", "adtRules", "taskPattern", 0.9],
    ],
  },
  {
    id: "Ex08",
    type: "exercise",
    title: "Binary trees, BST operations, paths and AVL rotations",
    weight: 1,
    concepts: [
      "binaryTreeTraps",
      "reconstructTree",
      "bst",
      "treeTraversal",
      "catalanBstShapes",
      "bstInsert",
      "bstInsertDoublePointer",
      "bstDelete",
      "bstDeleteCases",
      "printTreeLevels",
      "lrlp",
      "avl",
      "avlExactCases",
      "avlCases",
    ],
    taskTypes: ["drawDataStructure", "manualTrace", "writeC", "pseudocode"],
    strengthens: [
      ["reconstructTree", "treeTraversal", "usesMechanism", 0.82],
      ["bstDeleteCases", "bstDelete", "taskPattern", 0.9],
      ["avlExactCases", "avlCases", "taskPattern", 0.9],
    ],
  },
  {
    id: "Ex09",
    type: "exercise",
    title: "Hash-table drawing, probing, deletion repair and hash applications",
    weight: 1,
    concepts: [
      "chaining",
      "chainingOrder",
      "linearProbe",
      "doubleHash",
      "openAddress",
      "hashFunction",
      "searchChain",
      "deleteHash",
      "tombstoneRepair",
      "printOverlap",
      "targetSumHash",
    ],
    taskTypes: ["manualTrace", "writeC", "runtime", "edgeCase"],
    strengthens: [
      ["chaining", "chainingOrder", "taskPattern", 0.82],
      ["openAddress", "linearProbe", "usesMechanism", 0.88],
      ["deleteHash", "tombstoneRepair", "usesMechanism", 0.9],
    ],
  },
  {
    id: "Ex10",
    type: "exercise",
    title: "Dynamic programming helper tables",
    weight: 1,
    concepts: [
      "dpTemplate",
      "helperTable",
      "matrix",
      "palCuts",
      "matrixPath",
      "bigPlus",
      "lcs",
      "editDistance",
      "dpRuntimeMemory",
    ],
    taskTypes: ["fillHelperTable", "writeC", "runtime", "recurrence"],
    strengthens: [
      ["dpTemplate", "helperTable", "usesMechanism", 0.95],
      ["palCuts", "dpTemplate", "sameStatePattern", 0.9],
      ["bigPlus", "helperTable", "sameRepresentation", 0.86],
    ],
  },
  {
    id: "Ex11",
    type: "exercise",
    title: "Graph traversal, path counting and k-hop reasoning",
    weight: 0.95,
    concepts: [
      "bfs",
      "possibleBfsSequence",
      "dfs",
      "possibleDfsSequence",
      "cycle",
      "undirectedCycleDetection",
      "queue",
      "stack",
      "allPaths",
      "allSimplePathsCount",
      "khop",
      "kHopExact",
      "graphState",
      "adjacency",
    ],
    taskTypes: ["pseudocode", "manualTrace", "runtime"],
    strengthens: [
      ["bfs", "queue", "usesMechanism", 0.96],
      ["dfs", "allPaths", "usesMechanism", 0.78],
      ["bfs", "khop", "sameStatePattern", 0.86],
    ],
  },
  {
    id: "FS23-linked-list-procedureX",
    type: "pastExam",
    title: "Linked-list C procedure trace",
    weight: 0.75,
    concepts: ["linkedListRearrangementTrace", "linked", "pointers"],
    taskTypes: ["traceOutput", "manualTrace", "writeC"],
    strengthens: [
      ["linked", "linkedListRearrangementTrace", "taskPattern", 0.9],
    ],
  },
  {
    id: "FS23-BuildHeap-exchange-count",
    type: "pastExam",
    title: "BuildHeap exchange count",
    weight: 0.75,
    concepts: ["buildHeapExchangeCount", "buildHeap", "heapify"],
    taskTypes: ["manualTrace", "drawDataStructure"],
    strengthens: [["buildHeapExchangeCount", "heapify", "taskPattern", 0.92]],
  },
  {
    id: "FS23-red-black-historical",
    type: "pastExam",
    title: "Red-black historical warning",
    weight: 0.45,
    concepts: ["redBlackHistorical", "bst", "rotations"],
    taskTypes: ["drawDataStructure", "manualTrace"],
    strengthens: [["redBlackHistorical", "rotations", "examCooccurrence", 0.7]],
  },
  {
    id: "FS23-Master-method-none-case",
    type: "pastExam",
    title: "Master method non-applicability",
    weight: 0.7,
    concepts: ["master", "masterWorksheet", "recurrences"],
    taskTypes: ["recurrence", "runtime"],
    strengthens: [["master", "masterWorksheet", "taskPattern", 0.9]],
  },
  {
    id: "FS23-inversion-count",
    type: "pastExam",
    title: "Inversion counting",
    weight: 0.65,
    concepts: ["merge", "mergeHelper", "recurrences"],
    taskTypes: ["runtime", "pseudocode"],
    strengthens: [["merge", "mergeHelper", "usesMechanism", 0.75]],
  },
  {
    id: "FS23-logarithmic-nested-loops",
    type: "pastExam",
    title: "Logarithmic nested loops",
    weight: 0.7,
    concepts: ["logLoops", "nestedloops", "exactAnalysisWorkflow"],
    taskTypes: ["runtime"],
    strengthens: [["logLoops", "exactAnalysisWorkflow", "usesMechanism", 0.82]],
  },
  {
    id: "FS23-asymptotic-true-false",
    type: "pastExam",
    title: "Asymptotic true/false",
    weight: 0.7,
    concepts: ["bigO", "functionGrowthRanking", "bestWorstAvg"],
    taskTypes: ["runtime"],
    strengthens: [["bigO", "functionGrowthRanking", "sameProofPattern", 0.86]],
  },
  {
    id: "FS23-sieve-loop-bounds",
    type: "pastExam",
    title: "Sieve loop-bound trap",
    weight: 0.7,
    concepts: ["sieve", "boundaries", "nestedloops"],
    taskTypes: ["writeC", "runtime", "edgeCase"],
    strengthens: [["sieve", "boundaries", "taskPattern", 0.9]],
  },
  {
    id: "FS23-DFS-edge-classification",
    type: "pastExam",
    title: "DFS edge classification",
    weight: 0.75,
    concepts: ["dfsEdgeCode", "edgeTypes", "dfs", "graphState"],
    taskTypes: ["manualTrace", "pseudocode"],
    strengthens: [["dfs", "dfsEdgeCode", "taskPattern", 0.92]],
  },
  {
    id: "FS23-edit-distance-C",
    type: "pastExam",
    title: "Edit distance C-style DP",
    weight: 0.7,
    concepts: ["editDistance", "dpTemplate", "helperTable"],
    taskTypes: ["fillHelperTable", "writeC", "runtime"],
    strengthens: [["editDistance", "dpTemplate", "sameStatePattern", 0.9]],
  },
  {
    id: "FS23-stack-sorting",
    type: "pastExam",
    title: "Stack sorting under ADT rules",
    weight: 0.7,
    concepts: ["stackSort", "stack", "adtRules", "auxiliaryStack"],
    taskTypes: ["adtOnly", "pseudocode", "runtime"],
    strengthens: [["stackSort", "adtRules", "taskPattern", 0.9]],
  },
  {
    id: "FS24-Q1",
    type: "pastExam",
    title: "Backward run-length tracing",
    weight: 0.75,
    concepts: ["backwardRunLength", "scan", "boundaries", "arrayDecay"],
    taskTypes: ["traceOutput", "manualTrace", "edgeCase"],
    strengthens: [
      ["backwardRunLength", "scan", "taskPattern", 0.9],
      ["scan", "boundaries", "sameStatePattern", 0.75],
    ],
  },
  {
    id: "FS24-Q2-recursive-F-output",
    type: "pastExam",
    title: "Recursive F output trace",
    weight: 0.7,
    concepts: ["recursion", "traceOutput", "binaryPrint"],
    taskTypes: ["traceOutput", "recurrence"],
    strengthens: [["recursion", "traceOutput", "taskPattern", 0.8]],
  },
  {
    id: "FS24-Q3-recurrence-3T(n/3)+n",
    type: "pastExam",
    title: "Recurrence 3T(n/3)+n",
    weight: 0.7,
    concepts: ["recurrences", "master", "backwardSubstitution"],
    taskTypes: ["recurrence", "runtime"],
    strengthens: [["recurrences", "master", "usesMechanism", 0.86]],
  },
  {
    id: "FS24-Q4-min-pointer-changes",
    type: "pastExam",
    title: "Minimum pointer-change list task",
    weight: 0.75,
    concepts: ["linkedListRearrangementTrace", "linked", "pointers"],
    taskTypes: ["manualTrace", "writeC", "edgeCase"],
    strengthens: [
      ["linkedListRearrangementTrace", "pointers", "taskPattern", 0.9],
    ],
  },
  {
    id: "FS24-Q6",
    type: "pastExam",
    title: "Kth largest using only Stack ADT",
    weight: 0.9,
    concepts: [
      "stack",
      "adtRules",
      "kthLargestStack",
      "selectionLogic",
      "auxiliaryStack",
      "topKSelectionAnalysis",
    ],
    taskTypes: ["adtOnly", "runtime", "pseudocode"],
    strengthens: [
      ["stack", "adtRules", "examCooccurrence", 0.9],
      ["kthLargestStack", "selectionLogic", "sameStatePattern", 0.85],
      ["kthLargestStack", "auxiliaryStack", "usesMechanism", 0.9],
    ],
  },
  {
    id: "FS24-Q7-best-worst-log-loop",
    type: "pastExam",
    title: "Best/worst logarithmic loop by branch",
    weight: 0.7,
    concepts: ["logLoops", "bestWorstAvg", "exactAnalysisWorkflow"],
    taskTypes: ["runtime", "edgeCase"],
    strengthens: [["logLoops", "bestWorstAvg", "sameProofPattern", 0.82]],
  },
  {
    id: "FS24-Q-Dijkstra",
    type: "pastExam",
    title: "Dijkstra relaxation changes",
    weight: 0.85,
    concepts: [
      "dijkstra",
      "relaxation",
      "priorityQueue",
      "dijkstraTrace",
      "graphState",
    ],
    taskTypes: ["manualTrace", "runtime", "pseudocode"],
    strengthens: [
      ["dijkstra", "relaxation", "usesMechanism", 0.96],
      ["relaxation", "dijkstraTrace", "taskPattern", 0.85],
    ],
  },
  {
    id: "FS24-graph-simple-paths",
    type: "pastExam",
    title: "Graph simple paths",
    weight: 0.75,
    concepts: ["allPaths", "allSimplePathsCount", "dfs", "adjacency"],
    taskTypes: ["pseudocode", "runtime", "manualTrace"],
    strengthens: [["allPaths", "allSimplePathsCount", "taskPattern", 0.9]],
  },
  {
    id: "FS24-open-addressing-linear-probing",
    type: "pastExam",
    title: "Open addressing with linear probing",
    weight: 0.75,
    concepts: ["openAddress", "linearProbe", "deleteHash"],
    taskTypes: ["manualTrace", "edgeCase"],
    strengthens: [["openAddress", "linearProbe", "taskPattern", 0.9]],
  },
  {
    id: "FS24-Sort3",
    type: "pastExam",
    title: "Sort3 one-pass partitioning",
    weight: 0.75,
    concepts: ["sort3", "swap", "boundaries", "invariant"],
    taskTypes: ["writeC", "traceArray", "runtime"],
    strengthens: [["sort3", "invariant", "sameProofPattern", 0.84]],
  },
  {
    id: "FS24-maximum-product-three-values",
    type: "pastExam",
    title: "Maximum product of three values",
    weight: 0.65,
    concepts: ["selectionLogic", "scan", "edgeCases"],
    taskTypes: ["writeC", "runtime", "edgeCase"],
    strengthens: [["selectionLogic", "scan", "usesMechanism", 0.75]],
  },
  {
    id: "FS24-max-product-subarray",
    type: "pastExam",
    title: "Maximum product subarray DP",
    weight: 0.75,
    concepts: ["maxProduct", "dpTemplate", "edgeCases"],
    taskTypes: ["fillHelperTable", "runtime", "pseudocode"],
    strengthens: [["maxProduct", "dpTemplate", "sameStatePattern", 0.9]],
  },
  {
    id: "FS25-selection-sort",
    type: "pastExam",
    title: "Simple in-place selection sorting",
    weight: 0.75,
    concepts: ["selection", "swap", "scan", "invariant"],
    taskTypes: ["writeC", "traceArray", "runtime"],
    strengthens: [["selection", "swap", "usesMechanism", 0.82]],
  },
  {
    id: "FS25-sortK-frequency-array",
    type: "pastExam",
    title: "Frequency/direct-address sorting",
    weight: 0.85,
    concepts: [
      "counting",
      "frequencyArray",
      "directAddressing",
      "hashing",
      "arrayInitialization",
    ],
    taskTypes: ["writeC", "runtime", "edgeCase"],
    strengthens: [
      ["counting", "frequencyArray", "usesMechanism", 0.95],
      ["frequencyArray", "directAddressing", "sameRepresentation", 0.9],
    ],
  },
  {
    id: "FS25-Q-sortK",
    type: "pastExam",
    title: "Frequency/direct-address sorting alias",
    weight: 0.55,
    concepts: ["counting", "frequencyArray", "directAddressing"],
    taskTypes: ["writeC", "runtime", "edgeCase"],
    strengthens: [["counting", "frequencyArray", "usesMechanism", 0.86]],
  },
  {
    id: "FS25-HTInsert-chaining",
    type: "pastExam",
    title: "Chained hash insertion",
    weight: 0.75,
    concepts: ["chaining", "chainingOrder", "hashFunction"],
    taskTypes: ["manualTrace", "writeC"],
    strengthens: [["chaining", "chainingOrder", "taskPattern", 0.86]],
  },
  {
    id: "FS25-print-overlap",
    type: "pastExam",
    title: "Print overlap with hashing",
    weight: 0.75,
    concepts: ["printOverlap", "hashApps", "searchChain", "chaining"],
    taskTypes: ["writeC", "runtime"],
    strengthens: [["printOverlap", "hashApps", "taskPattern", 0.9]],
  },
  {
    id: "FS25-shortest-root-leaf-BFS",
    type: "pastExam",
    title: "Shortest root-leaf distance by queue/BFS",
    weight: 0.75,
    concepts: ["shortestRootLeaf", "queue", "bfs", "binaryTree"],
    taskTypes: ["pseudocode", "runtime"],
    strengthens: [["shortestRootLeaf", "queue", "usesMechanism", 0.9]],
  },
  {
    id: "FS25-shortest-root-leaf-recursive",
    type: "pastExam",
    title: "Shortest root-leaf distance recursively",
    weight: 0.7,
    concepts: ["shortestRootLeaf", "binaryTree", "recursion"],
    taskTypes: ["pseudocode", "runtime", "edgeCase"],
    strengthens: [["shortestRootLeaf", "recursion", "sameStatePattern", 0.75]],
  },
  {
    id: "FS25-substitution-proof-tree-runtime",
    type: "pastExam",
    title: "Substitution proof for tree runtime",
    weight: 0.7,
    concepts: ["substitution", "recurrences", "binaryTree"],
    taskTypes: ["recurrence", "runtime"],
    strengthens: [["substitution", "recurrences", "sameProofPattern", 0.85]],
  },
  {
    id: "FS25-nearest-zero-DP",
    type: "pastExam",
    title: "Nearest-zero dynamic programming",
    weight: 0.75,
    concepts: ["nearestZero", "dpTemplate", "matrix", "dpRuntimeMemory"],
    taskTypes: ["fillHelperTable", "runtime", "pseudocode"],
    strengthens: [["nearestZero", "dpTemplate", "sameStatePattern", 0.9]],
  },
];
