const concepts = [
  {
    id: "root",
    label: "INF II Semantic Exam Machine",
    kind: "core",
    domains: ["workflow", "proof"],
    taskTypes: ["runtime", "invariant", "writeC", "manualTrace"],
    summary:
      "A semantic learning graph for representation, mechanism, implementation, invariant, runtime and evidence.",
    priority: 3,
    anchor: { x: 0, y: 0 },
  },
  {
    id: "bubble",
    label: "Bubble Sort",
    kind: "algorithm",
    domains: ["sorting", "arrays"],
    mechanisms: ["adjacentComparison", "swap", "nestedloops"],
    representations: ["array"],
    proofPatterns: ["sortedSuffixInvariant"],
    taskTypes: ["writeC", "traceArray", "countComparisons", "runtime"],
    card: "bubble",
    sourceRefs: ["SL01", "Ex01"],
    summary: "Repeated adjacent compare-and-swap.",
    state: ["pass", "j", "unsorted prefix", "sorted suffix"],
    invariant: "After each pass, the largest remaining element is fixed.",
    runtime: "Theta(n^2) comparisons in the basic version.",
    edgeCases: ["n=0", "n=1", "already sorted", "reverse sorted"],
  },
  {
    id: "xsort",
    label: "XSort",
    kind: "algorithm",
    domains: ["sorting", "arrays"],
    mechanisms: ["swap", "boundaries", "bidirectional scan"],
    representations: ["array"],
    taskTypes: ["writeC", "traceArray", "manualTrace"],
    card: "xsort",
    sourceRefs: ["Ex01"],
    summary:
      "Bidirectional exchange sort pattern that combines boundary updates and swaps.",
  },
  {
    id: "heapSort",
    label: "HeapSort",
    kind: "algorithm",
    domains: ["sorting", "trees", "arrays"],
    mechanisms: ["swap", "heapify", "buildHeap"],
    representations: ["array", "heap"],
    proofPatterns: ["heapInvariant"],
    taskTypes: ["traceArray", "drawDataStructure", "runtime"],
    card: "heapSort",
    summary:
      "Array sorting by building a heap, swapping root with the end, and repairing downward.",
    state: ["heap size", "root", "last", "heapified prefix"],
    invariant: "Before each extraction, the active prefix is a valid heap.",
    runtime: "Theta(n log n) after linear-time BuildHeap.",
  },
  {
    id: "counting",
    label: "Counting Sort",
    kind: "algorithm",
    domains: ["sorting", "hashing", "arrays"],
    mechanisms: ["frequencyArray", "directAddressing", "scan"],
    representations: ["array", "frequency table"],
    taskTypes: ["writeC", "runtime", "edgeCase"],
    card: "counting",
    sourceRefs: ["FS25-Q-sortK"],
    summary:
      "Sort by counting occurrences in a direct-addressed frequency array.",
    runtime: "O(n + k), where k is the key range.",
  },
  {
    id: "kthLargestStack",
    label: "Kth Largest with Stack",
    kind: "examPattern",
    domains: ["stackQueue", "sorting"],
    mechanisms: ["stack", "selectionLogic", "auxiliaryStack", "adtRules"],
    representations: ["stack"],
    taskTypes: ["adtOnly", "pseudocode", "runtime"],
    card: "kthLargestStack",
    sourceRefs: ["FS24-Q6"],
    summary:
      "Selection under Stack ADT restrictions, using legal stack operations and auxiliary storage.",
    runtime:
      "Typically O(kn) or O(n log n)-style if a legal ordering strategy is used.",
  },
  {
    id: "selectionLogic",
    label: "selection logic",
    kind: "mechanism",
    domains: ["sorting", "proof"],
    taskTypes: ["runtime", "manualTrace"],
    summary:
      "Find an extremal or kth element by repeated scans, partitions, or restricted ADT passes.",
    anchor: { x: -140, y: -250 },
  },
  {
    id: "auxiliaryStack",
    label: "auxiliary stack",
    kind: "mechanism",
    domains: ["stackQueue", "pointers"],
    representations: ["stack"],
    taskTypes: ["adtOnly", "pseudocode"],
    summary:
      "Temporary stack used to preserve values while respecting legal ADT operations.",
    anchor: { x: -220, y: 250 },
  },
  {
    id: "stack",
    label: "Stack ADT",
    kind: "dataStructure",
    domains: ["stackQueue", "pointers"],
    mechanisms: ["push", "pop", "isEmpty"],
    representations: ["array", "linked list"],
    taskTypes: ["adtOnly", "writeC", "pseudocode"],
    card: "stack",
    summary:
      "Last-in-first-out ADT with restricted access through push and pop.",
    anchor: { x: -210, y: 330 },
  },
  {
    id: "queue",
    label: "Queue ADT",
    kind: "dataStructure",
    domains: ["stackQueue", "graphs"],
    mechanisms: ["enqueue", "dequeue"],
    representations: ["array", "linked list"],
    taskTypes: ["adtOnly", "pseudocode", "manualTrace"],
    card: "queue",
    summary: "First-in-first-out ADT that drives BFS-style layer traversal.",
    anchor: { x: -40, y: 390 },
  },
  {
    id: "bfs",
    label: "BFS",
    kind: "algorithm",
    domains: ["graphs", "stackQueue"],
    mechanisms: ["queue", "graphState", "visitedColor"],
    representations: ["graph"],
    proofPatterns: ["layerInvariant"],
    taskTypes: ["pseudocode", "manualTrace", "runtime"],
    card: "bfs",
    sourceRefs: ["Ex11"],
    summary: "Explore graph vertices by increasing unweighted distance layers.",
    state: ["queue", "color", "dist", "pred"],
    invariant:
      "When a vertex is dequeued, its shortest unweighted distance is known.",
    runtime: "O(V + E).",
  },
  {
    id: "dijkstra",
    label: "Dijkstra",
    kind: "algorithm",
    domains: ["weightedGraphs", "graphs"],
    mechanisms: ["relaxation", "priorityQueue", "graphState"],
    representations: ["weighted graph", "priority queue"],
    proofPatterns: ["greedyInvariant"],
    taskTypes: ["manualTrace", "runtime", "pseudocode"],
    card: "dijkstra",
    sourceRefs: ["FS24-Q-Dijkstra", "SL10"],
    summary:
      "Single-source shortest paths for nonnegative edge weights using extract-min and relaxation.",
    state: ["dist", "pred", "priority queue", "settled vertices"],
    invariant:
      "When a vertex is extracted, its shortest-path distance is final.",
    runtime: "Depends on priority queue representation.",
  },
  {
    id: "relaxation",
    label: "relaxation",
    kind: "mechanism",
    domains: ["weightedGraphs", "graphs"],
    taskTypes: ["manualTrace", "runtime"],
    summary:
      "Try to improve dist[v] through an edge (u,v) by comparing old and candidate distance.",
    anchor: { x: 330, y: 430 },
  },
  {
    id: "dpTemplate",
    label: "DP template",
    kind: "mechanism",
    domains: ["dp", "proof"],
    mechanisms: ["helperTable", "recurrence", "fillOrder"],
    taskTypes: ["fillHelperTable", "runtime", "invariant"],
    summary:
      "Define state meaning, recurrence, base cases, fill order, and reconstruction if needed.",
    anchor: { x: 260, y: 250 },
  },
  {
    id: "helperTable",
    label: "helper table",
    kind: "mechanism",
    domains: ["dp", "arrays"],
    representations: ["array", "matrix"],
    taskTypes: ["fillHelperTable", "writeC", "runtime"],
    summary:
      "Auxiliary array or matrix that stores solved subproblem values in DP.",
    anchor: { x: 220, y: 330 },
  },
  {
    id: "palCuts",
    label: "Palindrome Cuts DP",
    kind: "algorithm",
    domains: ["dp", "arrays"],
    mechanisms: ["helperTable", "recurrence", "fillOrder"],
    representations: ["string", "matrix"],
    taskTypes: ["fillHelperTable", "writeC", "runtime"],
    card: "palCuts",
    sourceRefs: ["Ex10"],
    summary:
      "Dynamic programming for minimum cuts using palindrome helper state and bottom-up loops.",
  },
  {
    id: "frequencyArray",
    label: "frequency array",
    kind: "mechanism",
    domains: ["hashing", "arrays", "sorting"],
    representations: ["array", "direct address table"],
    taskTypes: ["writeC", "runtime", "edgeCase"],
    summary:
      "Array indexed by key value to count occurrences or test direct-address membership.",
    anchor: { x: 170, y: -310 },
  },
  {
    id: "directAddressing",
    label: "direct addressing",
    kind: "representation",
    domains: ["hashing", "arrays"],
    representations: ["array"],
    taskTypes: ["writeC", "runtime", "edgeCase"],
    summary: "Use the key itself, or a shifted key, as an array slot address.",
    anchor: { x: 270, y: -300 },
  },
  {
    id: "swap",
    label: "swap / exchange",
    kind: "mechanism",
    domains: ["arrays", "sorting"],
    mechanisms: ["temporary variable"],
    representations: ["array"],
    taskTypes: ["writeC", "traceArray"],
    card: "swap",
    summary:
      "Exchange two values; central to bubble, selection, quick partition, heap sort and Sort3.",
    anchor: { x: -330, y: -340 },
  },
  {
    id: "heapify",
    label: "heapify",
    kind: "mechanism",
    domains: ["trees", "arrays", "sorting"],
    mechanisms: ["swap", "downwardRepair"],
    representations: ["array-as-tree", "heap"],
    taskTypes: ["manualTrace", "runtime", "drawDataStructure"],
    card: "heapify",
    summary:
      "Repair heap order by comparing a node with children and moving the violation downward.",
    anchor: { x: 310, y: -140 },
  },
  {
    id: "invariant",
    label: "invariant",
    kind: "proofPattern",
    domains: ["proof"],
    taskTypes: ["invariant", "runtime"],
    summary: "A maintained truth that connects algorithm state to correctness.",
    anchor: { x: 20, y: -130 },
  },
  {
    id: "algorithmProgramDataStructure",
    label: "algorithm vs program vs data structure",
    kind: "concept",
    domains: ["workflow"],
    taskTypes: ["pseudocode", "writeC"],
    summary:
      "Distinguish the abstract method, its C implementation and the representation it operates on.",
    priority: 0.6,
  },
  {
    id: "inputOutputSpec",
    label: "input/output specification",
    kind: "proofPattern",
    domains: ["workflow", "proof"],
    taskTypes: ["pseudocode", "edgeCase"],
    summary:
      "State valid inputs, returned outputs and corner-case behavior before choosing code.",
    priority: 0.8,
  },
  {
    id: "ambiguousSearchOutput",
    label: "ambiguous search output",
    kind: "examPattern",
    domains: ["arrays", "proof"],
    taskTypes: ["edgeCase", "traceArray"],
    summary:
      "Search specifications must say whether to return the first index, last index, Boolean result or not-found sentinel.",
    state: ["current index", "candidate answer", "not-found value"],
    priority: 0.8,
  },
  {
    id: "linearSearchVariants",
    label: "linear search variants",
    kind: "algorithm",
    domains: ["arrays"],
    taskTypes: ["writeC", "traceArray", "edgeCase"],
    summary:
      "One-pass search variants differ by loop condition, stop rule and returned index or Boolean.",
    state: ["i", "A[i]", "target", "found/not found"],
    runtime: "Theta(n) worst case; best case can be Theta(1).",
    priority: 1,
  },
  {
    id: "outOfBoundsWhile",
    label: "out-of-bounds while condition",
    kind: "examPattern",
    domains: ["arrays", "proof"],
    taskTypes: ["traceArray", "edgeCase", "writeC"],
    summary:
      "A search loop must test the array bound before reading A[i], otherwise missing targets can read past the array.",
    edgeCases: [
      "target absent",
      "empty array",
      "target after last valid index",
    ],
    priority: 0.9,
  },
  {
    id: "compileRunC",
    label: "compile and run C program",
    kind: "mechanism",
    domains: ["arrays"],
    taskTypes: ["traceOutput", "writeC"],
    summary:
      "Compile with gcc, run the executable and explain printed output from the executed C state.",
    state: ["source file", "executable", "argv/stdout", "return code"],
    priority: 0.8,
  },
  {
    id: "secondLargest",
    label: "second largest",
    kind: "algorithm",
    domains: ["arrays"],
    taskTypes: ["writeC", "traceArray", "edgeCase", "runtime"],
    summary:
      "Find the second largest value by two passes or one pass while preserving largest and second-largest state.",
    state: ["largest", "second largest", "current value"],
    runtime: "Theta(n).",
    edgeCases: ["n = 2", "duplicate values", "MIN sentinel"],
    priority: 1,
  },
  {
    id: "diagonalSum",
    label: "main diagonal sum",
    kind: "algorithm",
    domains: ["arrays"],
    representations: ["matrix"],
    taskTypes: ["writeC", "runtime"],
    summary:
      "Sum A[i][i] directly with one loop, or recognize the equivalent nested-loop if i == j version.",
    state: ["i", "A[i][i]", "sum"],
    runtime:
      "Theta(n) for an n by n matrix when using the direct diagonal loop.",
    priority: 0.9,
  },
  {
    id: "linearVsBinarySearch",
    label: "linear search vs binary search",
    kind: "examPattern",
    domains: ["arrays", "proof"],
    taskTypes: ["runtime", "edgeCase", "pseudocode"],
    summary:
      "Binary search needs sorted input and gives logarithmic search; linear search works without sortedness and scans.",
    runtime: "Linear search Theta(n); binary search Theta(log n).",
    edgeCases: [
      "missing target",
      "returned index vs Boolean",
      "duplicate target",
    ],
    priority: 1,
  },
  {
    id: "binaryInsertionSortNuance",
    label: "binary-search insertion-sort nuance",
    kind: "examPattern",
    domains: ["sorting", "proof"],
    taskTypes: ["runtime", "edgeCase"],
    summary:
      "Binary search can find the insertion position faster, but shifting still costs linear work per insertion.",
    runtime: "Worst-case insertion sort remains Theta(n^2).",
    priority: 0.9,
  },
  {
    id: "countOccurrenceSorted",
    label: "count occurrences with A1 unsorted and A2 sorted",
    kind: "algorithm",
    domains: ["arrays"],
    taskTypes: ["pseudocode", "runtime"],
    summary:
      "For each item in unsorted A1, binary-search sorted A2 without extra memory.",
    runtime: "Theta(n1 log n2).",
    priority: 0.9,
  },
  {
    id: "functionGrowthRanking",
    label: "function growth ranking",
    kind: "proofPattern",
    domains: ["proof"],
    taskTypes: ["runtime"],
    summary:
      "Rank constants, logarithms, roots, polynomials, exponentials and factorials by asymptotic growth.",
    priority: 0.9,
  },
  {
    id: "coupledLoopSum",
    label: "exact coupled-loop sum",
    kind: "proofPattern",
    domains: ["proof", "arrays"],
    taskTypes: ["runtime"],
    summary:
      "When the inner bound depends on the outer index, write the summation before simplifying.",
    state: ["outer index", "inner bound", "summation"],
    priority: 0.9,
  },
  {
    id: "taRecurrence",
    label: "Ta(n)=2Ta(n-1)+c1",
    kind: "proofPattern",
    domains: ["recursion", "proof"],
    taskTypes: ["recurrence", "runtime"],
    summary:
      "A recurrence solved by printing values, guessing exponential growth and proving by substitution.",
    runtime: "O(2^n) style bound under the taught substitution proof.",
    priority: 0.8,
  },
  {
    id: "backwardSubstitution",
    label: "backward substitution",
    kind: "proofPattern",
    domains: ["recursion", "proof"],
    taskTypes: ["recurrence", "runtime"],
    summary:
      "Expand a recurrence repeatedly, stop at the base case and sum the resulting level costs.",
    priority: 0.8,
  },
  {
    id: "masterWorksheet",
    label: "Master Method worksheet",
    kind: "proofPattern",
    domains: ["recursion", "proof"],
    taskTypes: ["recurrence", "runtime"],
    summary:
      "Identify a, b and f(n), compare with n^(log_b a), and know when no Master case applies.",
    priority: 0.9,
  },
  {
    id: "dynamicArrayGrowth",
    label: "dynamic array growth",
    kind: "proofPattern",
    domains: ["arrays", "proof"],
    taskTypes: ["runtime", "edgeCase"],
    summary:
      "Compare additive growth with geometric resizing by tracking copy cost and amortized behavior.",
    runtime:
      "Geometric growth gives constant amortized append; additive growth does not.",
    priority: 0.8,
  },
  {
    id: "heapTraceTable",
    label: "heap trace table",
    kind: "examPattern",
    domains: ["sorting", "trees", "arrays"],
    taskTypes: ["manualTrace", "drawDataStructure"],
    summary:
      "Trace active heap size, root/last exchanges, heapify path and array state after each exchange.",
    state: ["active heap size", "root", "last", "heapify path", "array"],
    priority: 1,
  },
  {
    id: "buildHeapExchangeCount",
    label: "BuildHeap exchange count",
    kind: "examPattern",
    domains: ["sorting", "trees"],
    taskTypes: ["manualTrace", "drawDataStructure"],
    summary:
      "Count only actual exchanges while heapifying from the last internal node to the root.",
    state: ["heapify index", "selected child", "exchange count"],
    priority: 1,
  },
  {
    id: "daryHeapIndexing",
    label: "d-ary heap index formulas",
    kind: "mechanism",
    domains: ["trees", "arrays"],
    taskTypes: ["writeC", "edgeCase"],
    summary:
      "Use the correct 0-based or 1-based parent and child formulas before writing heap code.",
    edgeCases: ["0-based vs 1-based convention", "last partial child range"],
    priority: 0.8,
  },
  {
    id: "dualPivotTrace",
    label: "dual-pivot quicksort trace",
    kind: "examPattern",
    domains: ["sorting", "arrays"],
    taskTypes: ["manualTrace", "traceArray", "runtime"],
    summary:
      "Track pivot order, three partition regions, lt/i/gt state and final pivot placement.",
    state: ["p1", "p2", "lt", "i", "gt", "three regions"],
    priority: 1,
  },
  {
    id: "quicksortAssumptions",
    label: "quicksort assumptions",
    kind: "proofPattern",
    domains: ["sorting", "proof"],
    taskTypes: ["runtime", "edgeCase"],
    summary:
      "Partition quality controls quicksort runtime; randomized pivots reduce worst-case exposure.",
    runtime: "Average Theta(n log n), worst Theta(n^2).",
    priority: 0.8,
  },
  {
    id: "pointerPrintAddresses",
    label: "address printed by %p",
    kind: "examPattern",
    domains: ["pointers"],
    taskTypes: ["traceOutput", "manualTrace"],
    summary:
      "Distinguish &a, the address stored in p, &p and the value obtained by dereferencing p.",
    state: ["&a", "p", "&p", "*p"],
    priority: 1,
  },
  {
    id: "mallocCopyFree",
    label: "malloc-copy-free",
    kind: "mechanism",
    domains: ["pointers"],
    taskTypes: ["writeC", "traceOutput", "edgeCase"],
    summary:
      "Copy a heap value into a normal variable before free; the copied variable keeps its value.",
    state: ["allocated cell", "*p", "copied variable", "free(p)"],
    priority: 0.9,
  },
  {
    id: "cPassByValue",
    label: "C passes by value",
    kind: "concept",
    domains: ["pointers"],
    taskTypes: ["traceOutput", "writeC", "edgeCase"],
    summary:
      "A function receives copies of arguments; caller mutation requires passing addresses and dereferencing them.",
    priority: 1,
  },
  {
    id: "arrayAssignmentInvalid",
    label: "array assignment invalid",
    kind: "examPattern",
    domains: ["pointers", "arrays"],
    taskTypes: ["writeC", "edgeCase"],
    summary:
      "Array variables cannot be assigned like scalars, while pointer variables can store A or &A[0].",
    edgeCases: [
      "int b[3] = a is invalid",
      "p = a is valid",
      "*(a+1) equals a[1]",
    ],
    priority: 0.9,
  },
  {
    id: "pointerOffsetSwap",
    label: "pointer-offset swap",
    kind: "examPattern",
    domains: ["pointers", "arrays"],
    taskTypes: ["traceArray", "writeC"],
    summary:
      "Calling a swap helper with &A[1] changes the effective base address, so index meanings shift.",
    state: ["base pointer", "logical index", "physical array slot"],
    priority: 1,
  },
  {
    id: "dynamicReversePrependOwnership",
    label: "dynamic reverse/prepend ownership",
    kind: "mechanism",
    domains: ["pointers", "arrays"],
    taskTypes: ["writeC", "edgeCase"],
    summary:
      "Allocate new arrays for reverse/prepend tasks, preserve size, and avoid returning pointers to local arrays.",
    edgeCases: [
      "free old array when appropriate",
      "preserve n or n+1",
      "NULL allocation",
    ],
    priority: 0.8,
  },
  {
    id: "arrayToLinkedList",
    label: "array-to-linked-list",
    kind: "mechanism",
    domains: ["pointers", "stackQueue"],
    taskTypes: ["writeC", "edgeCase"],
    summary:
      "Allocate one node per array element, preserve order with head insertion or a tail pointer, and define freeing responsibility.",
    priority: 0.8,
  },
  {
    id: "linkedListRearrangementTrace",
    label: "linked-list rearrangement trace",
    kind: "examPattern",
    domains: ["pointers"],
    taskTypes: ["manualTrace", "traceOutput", "writeC"],
    summary:
      "Trace h, cur, t and next variables, saving next before relinking and minimizing pointer changes.",
    state: ["head", "current", "next", "tail/temp", "rewired next fields"],
    priority: 1,
  },
  {
    id: "stackOperationSequence",
    label: "stack operation sequence drawing",
    kind: "examPattern",
    domains: ["stackQueue"],
    taskTypes: ["adtOnly", "manualTrace"],
    summary:
      "Draw the stack after each push/pop and respect the LIFO top-only access rule.",
    state: ["top", "items", "operation"],
    priority: 0.8,
  },
  {
    id: "queueOperationSequence",
    label: "queue operation sequence drawing",
    kind: "examPattern",
    domains: ["stackQueue"],
    taskTypes: ["adtOnly", "manualTrace"],
    summary:
      "Draw the queue after each enqueue/dequeue and preserve FIFO order.",
    state: ["front", "rear", "items", "operation"],
    priority: 0.8,
  },
  {
    id: "arrayStackImplementation",
    label: "array stack implementation",
    kind: "dataStructure",
    domains: ["stackQueue", "arrays"],
    taskTypes: ["writeC", "edgeCase"],
    summary:
      "Implement stack state with an array and top index, checking empty and full cases.",
    runtime: "Push and pop are O(1).",
    priority: 0.8,
  },
  {
    id: "arrayCircularQueueImplementation",
    label: "array circular queue implementation",
    kind: "dataStructure",
    domains: ["stackQueue", "arrays"],
    taskTypes: ["writeC", "edgeCase"],
    summary:
      "Implement queue state with front, rear and size using modular arithmetic.",
    runtime: "Enqueue and dequeue are O(1).",
    priority: 0.8,
  },
  {
    id: "binaryTreeTraps",
    label: "binary tree true/false traps",
    kind: "examPattern",
    domains: ["trees"],
    taskTypes: ["manualTrace", "edgeCase"],
    summary:
      "Separate general binary-tree traversal facts from BST-specific ordering facts.",
    edgeCases: [
      "inorder sorted only for BST",
      "unique-value assumptions",
      "leaf order in traversals",
    ],
    priority: 0.9,
  },
  {
    id: "bstInsertDoublePointer",
    label: "BST insert with TreeNode**",
    kind: "mechanism",
    domains: ["trees", "pointers"],
    taskTypes: ["writeC", "edgeCase"],
    summary:
      "Use a pointer-to-pointer when insertion may change the root or a child link directly.",
    state: ["TreeNode **slot", "allocated node", "parent link"],
    priority: 0.8,
  },
  {
    id: "bstDeleteCases",
    label: "BST delete full cases",
    kind: "examPattern",
    domains: ["trees", "pointers"],
    taskTypes: ["writeC", "manualTrace", "edgeCase"],
    summary:
      "Handle leaf, one-child, root and two-child deletion under the chosen predecessor/successor policy.",
    edgeCases: [
      "delete root",
      "two children",
      "predecessor vs successor policy",
    ],
    priority: 1,
  },
  {
    id: "avlExactCases",
    label: "AVL exact exercise cases",
    kind: "examPattern",
    domains: ["trees"],
    taskTypes: ["manualTrace", "drawDataStructure", "writeC"],
    summary:
      "Identify LL, RR, LR and RL cases, update heights bottom-up and return the new subtree root.",
    state: ["X", "Y", "Z", "balance factors", "new subtree root"],
    priority: 1,
  },
  {
    id: "graphTerminologyTraps",
    label: "graph terminology trap cards",
    kind: "examPattern",
    domains: ["graphs"],
    taskTypes: ["manualTrace", "edgeCase"],
    summary:
      "Distinguish directed vs undirected, cycle vs simple path, DAG, connectedness and adjacency-matrix meaning.",
    priority: 0.8,
  },
  {
    id: "possibleBfsSequence",
    label: "possible BFS sequence",
    kind: "examPattern",
    domains: ["graphs"],
    taskTypes: ["manualTrace", "pseudocode"],
    summary:
      "A BFS order may vary by adjacency order, but it must respect layer distances.",
    state: ["queue", "distance layer", "adjacency order"],
    priority: 0.9,
  },
  {
    id: "possibleDfsSequence",
    label: "possible DFS sequence",
    kind: "examPattern",
    domains: ["graphs"],
    taskTypes: ["manualTrace", "pseudocode"],
    summary:
      "A DFS order may vary by adjacency order, but it must follow depth-before-sibling exploration.",
    state: ["recursion stack", "color", "adjacency order"],
    priority: 0.9,
  },
  {
    id: "undirectedCycleDetection",
    label: "undirected cycle detection",
    kind: "algorithm",
    domains: ["graphs"],
    taskTypes: ["pseudocode", "runtime"],
    summary:
      "Run DFS and report a cycle when a visited neighbor is not the current predecessor.",
    runtime: "O(V + E).",
    priority: 0.8,
  },
  {
    id: "allSimplePathsCount",
    label: "all simple paths count",
    kind: "algorithm",
    domains: ["graphs"],
    taskTypes: ["pseudocode", "runtime"],
    summary:
      "Use path-local visited state, unmark on backtracking, and count or print all simple paths.",
    runtime:
      "Exponential in the worst case because the output can be exponential.",
    priority: 0.9,
  },
  {
    id: "kHopExact",
    label: "k-hop exactly k",
    kind: "examPattern",
    domains: ["graphs"],
    taskTypes: ["pseudocode", "manualTrace"],
    summary:
      "Use BFS distances and output vertices with distance exactly k, not at most k.",
    edgeCases: ["unreachable vertices", "directed edges", "k = 0"],
    priority: 0.9,
  },
  {
    id: "weightedGraphDefinition",
    label: "weighted graph definition",
    kind: "concept",
    domains: ["weightedGraphs"],
    taskTypes: ["pseudocode", "edgeCase"],
    summary:
      "A weighted graph has an edge-weight function and may be directed or undirected depending on the problem.",
    priority: 0.7,
  },
  {
    id: "mstVsSssp",
    label: "MST vs SSSP",
    kind: "examPattern",
    domains: ["weightedGraphs"],
    taskTypes: ["manualTrace", "edgeCase"],
    summary:
      "MST minimizes total tree weight; SSSP minimizes source-to-vertex distances, and neither structure implies the other.",
    priority: 0.9,
  },
  {
    id: "spanningTree",
    label: "spanning tree",
    kind: "concept",
    domains: ["weightedGraphs", "graphs"],
    taskTypes: ["manualTrace", "edgeCase"],
    summary:
      "A spanning tree contains all vertices, is acyclic, has |V|-1 edges and assumes connectedness.",
    priority: 0.7,
  },
  {
    id: "safeEdge",
    label: "safe edge",
    kind: "proofPattern",
    domains: ["weightedGraphs", "proof"],
    taskTypes: ["invariant", "manualTrace"],
    summary:
      "An edge is safe for a partial MST if adding it preserves the existence of some MST containing the partial set.",
    priority: 0.8,
  },
  {
    id: "cutLightEdgeProof",
    label: "cut/light-edge theorem proof",
    kind: "proofPattern",
    domains: ["weightedGraphs", "proof"],
    taskTypes: ["invariant", "runtime"],
    summary:
      "A light edge crossing a cut that respects the partial MST is safe, by the standard exchange proof.",
    priority: 0.9,
  },
  {
    id: "minimumEdgeMstProof",
    label: "minimum-weight edge belongs to some MST",
    kind: "proofPattern",
    domains: ["weightedGraphs", "proof"],
    taskTypes: ["invariant", "edgeCase"],
    summary:
      "Use an exchange argument to construct an MST containing a chosen minimum-weight edge, with ties allowed.",
    priority: 0.7,
  },
  {
    id: "arrayInitialization",
    label: "array initialization",
    kind: "mechanism",
    domains: ["arrays"],
    taskTypes: ["writeC", "edgeCase"],
    summary:
      "Initialize all array slots before frequency counting, probing or DP table filling.",
    priority: 0.7,
  },
  {
    id: "traceOutput",
    label: "trace printed output",
    kind: "examPattern",
    domains: ["workflow"],
    taskTypes: ["traceOutput", "manualTrace"],
    summary:
      "Track exact control flow and state updates to determine the printed output.",
    state: ["current line", "variables", "print events"],
    priority: 0.8,
  },
  {
    id: "backwardRunLength",
    label: "backward run-length tracing",
    kind: "examPattern",
    domains: ["arrays"],
    taskTypes: ["traceOutput", "manualTrace", "edgeCase"],
    card: "backwardRunLength",
    summary:
      "Scan from the end, track current value and run length, print when a run ends and after the loop.",
    state: ["i", "A[i]", "num", "count", "print event"],
    priority: 1,
  },
  {
    id: "hilbertDrawingRecursion",
    label: "Hilbert drawing recursion",
    kind: "algorithm",
    domains: ["recursion"],
    taskTypes: ["traceOutput", "recurrence"],
    card: "hilbertDrawingRecursion",
    summary:
      "Recursive Hilbert drawing has four smaller drawing calls plus constant turn/connector work.",
    runtime: "T(n)=4T(n-1)+O(1) for drawing-call count.",
    priority: 0.9,
  },
  {
    id: "hilbertLengthRecurrence",
    label: "Hilbert length recurrence",
    kind: "proofPattern",
    domains: ["recursion", "proof"],
    taskTypes: ["recurrence", "runtime"],
    card: "hilbertLengthRecurrence",
    summary:
      "The Ex01 curve-length recurrence is H(i)=2H(i-1)+3*l/2^i with H(0)=0.",
    state: ["order i", "previous length", "connector length"],
    priority: 1,
  },
];
